[package]
edition = "2021"
name = "boardgame-core"
version = "0.1.0"

[dependencies]
anyhow = "1.0.95"
rusqlite = { version = "0.33.0", features = ["bundled"] }
thiserror = "2.0.11"

[dev-dependencies]
tempfile = "3.8"
